### PR TITLE
Add new website

### PR DESCRIPTION
**Pull request by lulf**
Proposal for enmasse.io redesign to make it more modern and appealing. The documentation page is now 'included' in the same theme style as the main page. The new design also allows for more interactive content like videos. The icons are self made and based on icons provided by red hat. Some of the content has been modified to match the new layout, and there are some assumptions regarding 1.0 in there :)  We should also consider splitting into more guides, but that can be done separately.

The changes also include a simplification where it is assumed that the documentation for each enmasse release (+ master) is pushed as part of the enmasse repo github actions. This makes it a bit simpler to make edits, and also allows master builds to add doc publishing as a step that must succeed. Changes to pushing docs will come to the main repo if this PR is accepted. This also requires stopping the travis job that periodically syncs the website.

I will demo this on a meeting, but here are some screenshot previews:

Screenshot from 2020-05-22 13-23-28
Screenshot from 2020-05-22 13-23-56
Screenshot from 2020-05-22 13-24-08
Screenshot from 2020-05-22 13-24-17
Screenshot from 2020-05-22 13-24-30
Screenshot from 2020-05-22 13-24-38

### CODE REVIEW

**Comment by anukritijha** [comment]
@lulf Looks great, I was wondering if we should also add a section for our upcoming major releases?

**Comment by ctron** [comment]
This looks awesome!

Just a few things:
* The blue of the header bar looks a bit darker than the dark blue in the EnMasse logo … not sure that is intentional. I still like the color.
* I absolutely like that we have Eclipse Hono on board. However, officially it is "Eclipse Hono™" :) … beside, the claim of EnMasse is, that it is Apache 2.0 licensed. However Hono is EPLv2 licensed.
* What do you think about an "adopters"  section? We could go ahead and ask around who would be OK with mentioning.

**Comment by lulf** [comment]
@ctron I've fixed up the specific comments. Regarding 'adopters' section, I very much agree. I think we need to think about who to list and how to present it. I see Strimzi has a section on the front page "Is used by", which I think is sort of at the proper level.

**Comment by lulf** [comment]
@anukritijha Regarding future releases, which page are you thinking would be most approriate for this content? A separate page or maybe in downloads?  We did try to maintain a roadmap document in the main repo some time ago, but it got stale quickly. It would be nice if we could come up with a way to make this manageable. I also think maybe this sort of things are better managed in some kind of project board that can also be setup for github (I see strimzi is using this for instance).

**Comment by lulf** [comment]
Updates screenshot with changes.

preview2
preview2-2

**Pull request merged**
